#!/usr/bin/env ruby

require 'rubygems'
require 'djinn'
require 'mongoid'

require File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

TweetEngine.config = YAML.load_file("#{Rails.root}/config/tweet_engine.yml")[Rails.env]

# @TODO: Get database name from config file
Mongoid.configure do |config|
  name = "tweet_engine_#{Rails.env}"
  config.master = Mongo::Connection.new.db(name)
  config.persist_in_safe_mode = false
end

class TweetDjinn

  include Djinn

  djinn do

    start do
      log "Using keywords #{TweetEngine.config['keywords']}"
      log "You current have #{TweetEngine::PotentialFollower.all.count} potential followers"
      
      @tweeple_search = TweetEngine::SearchJob.new
      loop do
        log "Searching for more tweeple"
        @tweeple_search.searching
        log "Now have #{TweetEngine::PotentialFollower.all.count} potential followers"
        sleep 15.minutes.to_i
      end
    end

    stop do
      log "Djinn is stopping.."
    end

    exit do
      log "Stopping search.."
    end
  end

end

TweetDjinn.djinnify