#!/usr/bin/env ruby

require 'rubygems'

require File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

TweetStack.config = YAML.load_file("#{Rails.root}/config/tweet_stack.yml")[Rails.env]

Mongoid.configure do |config|
  name = "dummy_#{Rails.env}"
  config.master = Mongo::Connection.new.db(name)
  config.persist_in_safe_mode = false
end

class TweetDjinn

  include Djinn

  djinn do

    start do
      log "You current have #{TweetStack::PotentialFollower.all.count} potential followers"
      
      @tweeple_search = TweetStack::SearchJob.new
      loop do
        log "Searching for more tweeple"
        @tweeple_search.searching
        log "Now have #{TweetStack::PotentialFollower.all.count} potential followers"
        sleep 15.minutes.to_i
      end
    end

    stop do
      log "Djinn is stopping.."
    end

    exit do
      log "Stopping search.."
    end
  end

end

TweetDjinn.djinnify